require 'json'

def usage()
	puts "reads through generated twitter feed files and prints the date and text of the tweet."
	puts "to run, you will need to know how many files were generated by aggitator.rb - you can redirect the output to a file as needed."
	puts "ruby aggregator.rb <twitter_handle> <num_files>"
	puts "example: ruby aggregator.rb realDonaldTrump 17 > trump_tweets.txt"
	raise "please retry with correct parameters"
end
twitter_handle = ARGV[0] || usage
num_files = ARGV[1] || usage

for i in 0..num_files.to_i - 1
  file = File.read("#{twitter_handle}_#{i}.json")
  tweets = JSON.parse(file)

  tweets.each do | tweet |
    date = tweet['created_at']
    text = tweet['text']
    puts date + " | " + text
  end
end